---
  -
    name: 'play1'
    hosts: web_servers
    tasks:
      -
         name: 'install apache on the web servers'
         yum:
            name: httpd
            state: latest
      -
         name: 'start apache'
         service:
           name: httpd
           state: started
           enabled: yes
